language: python

python:
    - "3.4"
    - "3.5"
    - "3.6"

install: 
    - pip install -r requirements/requirements.txt
    - pip install -r requirements/test-requirements.txt
    - pip install coveralls

script: 
    - nosetests
    - coverage run --source=PYEVALB setup.py test

after_success:
    coveralls
